default_platform(:android)

platform :android do
  desc "Fetch localizations"
  lane :localize do
    google_sheet_localize(
        service_account_path: "./fastlane/google_drive_credentials.json",
        sheet_id: "1nNIq7ULcSUd3CbUleBtMgp2WxGupWcbHOWvCwRlPnZs",
        language_titles: ["de", "en"],
        default_language: "en",
        base_language: "en",
        localization_path: "./app/src/main/res/"
      )
  end

  desc "Builds a new version and pushes it to repository"
  lane :build do
    gradle(task: "test ktlintFormat clean")
    increment_version_code_and_commit lane:self.runner.current_lane
    gradle(task: ":app:bundleRelease")
  end

  desc "Builds a new version, pushes it to repository and deploys it to beta track"
    lane :beta do
      gradle(task: "test ktlintFormat")
      increment_version_code_and_commit lane:self.runner.current_lane
      gradle(task: "clean bundleRelease")
      upload_to_play_store(
        track: "beta",
        skip_upload_apk: true,
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_screenshots: true
      )
    end
end

desc "Tags the current commit with the tag name"
private_lane :tagCurrentVersion do |options|
  add_git_tag(tag: get_tag_name(options))
end

def increment_version_code_and_commit(options)
  android_set_version_code
  git_commit(path: ".", message: "New Version: " + get_tag_name(options))
  tagCurrentVersion options
  push_to_git_remote(remote_branch: git_branch)
end

def get_tag_name(options)
  return "v" + android_get_version_name + "-b" + android_get_version_code
end