import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val appcompat: String = "androidx.appcompat:appcompat:" + Versions.appcompat

    /**
     * http://tools.android.com
     */
    const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:" +
            Versions.constraintlayout

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val core_ktx: String = "androidx.core:core-ktx:" + Versions.core_ktx

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val fragment: String = "androidx.fragment:fragment:" + Versions.fragment

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val lifecycle_compiler: String = "androidx.lifecycle:lifecycle-compiler:" +
            Versions.androidx_lifecycle

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val lifecycle_extensions: String = "androidx.lifecycle:lifecycle-extensions:" +
            Versions.androidx_lifecycle

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val navigation_fragment_ktx: String = "androidx.navigation:navigation-fragment-ktx:" +
            Versions.androidx_navigation

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val navigation_safe_args_gradle_plugin: String =
            "androidx.navigation:navigation-safe-args-gradle-plugin:" + Versions.androidx_navigation

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val navigation_ui_ktx: String = "androidx.navigation:navigation-ui-ktx:" +
            Versions.androidx_navigation

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val work_runtime: String = "androidx.work:work-runtime:" + Versions.androidx_work

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val work_rxjava2: String = "androidx.work:work-rxjava2:" + Versions.androidx_work

    /**
     * https://github.com/floschu/Koordinator
     */
    const val koordinator_android_koin: String =
            "at.florianschuster.koordinator:koordinator-android-koin:" +
            Versions.koordinator_android_koin

    /**
     * https://github.com/floschu/Reaktor
     */
    const val reaktor_android_koin: String = "at.florianschuster.reaktor:reaktor-android-koin:" +
            Versions.reaktor_android_koin

    /**
     * https://github.com/akaita/easylauncher-gradle-plugin
     */
    const val easylauncher: String = "com.akaita.android:easylauncher:" + Versions.easylauncher

    /**
     * https://github.com/alexvasilkov/GestureViews
     */
    const val gesture_views: String = "com.alexvasilkov:gesture-views:" + Versions.gesture_views

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val customtabs: String = "com.android.support:customtabs:" + Versions.customtabs

    /**
     * https://developer.android.com/studio
     */
    const val aapt2: String = "com.android.tools.build:aapt2:" + Versions.aapt2

    const val bundletool: String = "com.android.tools.build:bundletool:" + Versions.bundletool

    /**
     * https://developer.android.com/studio
     */
    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
            Versions.com_android_tools_build_gradle

    /**
     * https://developer.android.com/studio
     */
    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

    const val crashlytics: String = "com.crashlytics.sdk.android:crashlytics:" +
            Versions.crashlytics

    /**
     * http://facebook.github.io/shimmer-android
     */
    const val shimmer: String = "com.facebook.shimmer:shimmer:" + Versions.shimmer

    /**
     * https://github.com/bumptech/glide
     */
    const val com_github_bumptech_glide_compiler: String = "com.github.bumptech.glide:compiler:" +
            Versions.com_github_bumptech_glide

    /**
     * https://github.com/bumptech/glide
     */
    const val glide: String = "com.github.bumptech.glide:glide:" +
            Versions.com_github_bumptech_glide

    /**
     * https://github.com/tbruyelle/RxPermissions
     */
    const val rxpermissions: String = "com.github.tbruyelle:rxpermissions:" + Versions.rxpermissions

    const val play_services_auth: String = "com.google.android.gms:play-services-auth:" +
            Versions.play_services_auth

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val material: String = "com.google.android.material:material:" + Versions.material

    const val com_google_android_play_core: String = "com.google.android.play:core:" +
            Versions.com_google_android_play_core

    /**
     * https://github.com/google/gson
     */
    const val gson: String = "com.google.code.gson:gson:" + Versions.gson

    const val firebase_auth: String = "com.google.firebase:firebase-auth:" + Versions.firebase_auth

    const val firebase_core: String = "com.google.firebase:firebase-core:" + Versions.firebase_core

    const val firebase_dynamic_links: String = "com.google.firebase:firebase-dynamic-links:" +
            Versions.firebase_dynamic_links

    const val firebase_firestore: String = "com.google.firebase:firebase-firestore:" +
            Versions.firebase_firestore

    const val firebase_messaging: String = "com.google.firebase:firebase-messaging:" +
            Versions.firebase_messaging

    const val firebase_perf: String = "com.google.firebase:firebase-perf:" + Versions.firebase_perf

    const val google_services: String = "com.google.gms:google-services:" + Versions.google_services

    /**
     * https://github.com/zxing/zxing
     */
    const val com_google_zxing_core: String = "com.google.zxing:core:" +
            Versions.com_google_zxing_core

    /**
     * https://github.com/JakeWharton/RxBinding/
     */
    const val rxbinding_appcompat: String = "com.jakewharton.rxbinding3:rxbinding-appcompat:" +
            Versions.com_jakewharton_rxbinding3

    /**
     * https://github.com/JakeWharton/RxBinding/
     */
    const val rxbinding_core: String = "com.jakewharton.rxbinding3:rxbinding-core:" +
            Versions.com_jakewharton_rxbinding3

    /**
     * https://github.com/JakeWharton/RxBinding/
     */
    const val rxbinding_material: String = "com.jakewharton.rxbinding3:rxbinding-material:" +
            Versions.com_jakewharton_rxbinding3

    /**
     * https://github.com/JakeWharton/RxBinding/
     */
    const val rxbinding_recyclerview: String =
            "com.jakewharton.rxbinding3:rxbinding-recyclerview:" +
            Versions.com_jakewharton_rxbinding3

    /**
     * https://github.com/JakeWharton/RxBinding/
     */
    const val rxbinding: String = "com.jakewharton.rxbinding3:rxbinding:" +
            Versions.com_jakewharton_rxbinding3

    const val rxrelay: String = "com.jakewharton.rxrelay2:rxrelay:" + Versions.rxrelay

    /**
     * https://github.com/JakeWharton/ThreeTenABP/
     */
    const val threetenabp: String = "com.jakewharton.threetenabp:threetenabp:" +
            Versions.threetenabp

    /**
     * https://github.com/JakeWharton/timber
     */
    const val timber: String = "com.jakewharton.timber:timber:" + Versions.timber

    const val zxing_android_embedded: String = "com.journeyapps:zxing-android-embedded:" +
            Versions.zxing_android_embedded

    /**
     * https://github.com/mikepenz/AboutLibraries
     */
    const val aboutlibraries: String = "com.mikepenz:aboutlibraries:" + Versions.aboutlibraries

    /**
     * https://github.com/orhanobut/hawk
     */
    const val hawk: String = "com.orhanobut:hawk:" + Versions.hawk

    /**
     * https://github.com/pinterest/ktlint
     */
    const val ktlint: String = "com.pinterest:ktlint:" + Versions.ktlint

    /**
     * http://github.com/square/leakcanary/
     */
    const val leakcanary_android: String = "com.squareup.leakcanary:leakcanary-android:" +
            Versions.leakcanary_android

    /**
     * https://github.com/square/okhttp
     */
    const val logging_interceptor: String = "com.squareup.okhttp3:logging-interceptor:" +
            Versions.com_squareup_okhttp3

    /**
     * https://github.com/square/okhttp
     */
    const val okhttp: String = "com.squareup.okhttp3:okhttp:" + Versions.com_squareup_okhttp3

    /**
     * https://github.com/square/retrofit/
     */
    const val adapter_rxjava2: String = "com.squareup.retrofit2:adapter-rxjava2:" +
            Versions.com_squareup_retrofit2

    /**
     * https://github.com/square/retrofit/
     */
    const val converter_gson: String = "com.squareup.retrofit2:converter-gson:" +
            Versions.com_squareup_retrofit2

    /**
     * https://github.com/square/retrofit/
     */
    const val retrofit: String = "com.squareup.retrofit2:retrofit:" +
            Versions.com_squareup_retrofit2

    /**
     * https://github.com/tailoredmedia/AndroidAppUtil
     */
    const val util_async: String = "com.tailoredapps.androidutil:util-async:" +
            Versions.com_tailoredapps_androidutil

    /**
     * https://github.com/tailoredmedia/AndroidAppUtil
     */
    const val util_firebase: String = "com.tailoredapps.androidutil:util-firebase:" +
            Versions.com_tailoredapps_androidutil

    /**
     * https://github.com/tailoredmedia/AndroidAppUtil
     */
    const val util_network: String = "com.tailoredapps.androidutil:util-network:" +
            Versions.com_tailoredapps_androidutil

    /**
     * https://github.com/tailoredmedia/AndroidAppUtil
     */
    const val util_optional: String = "com.tailoredapps.androidutil:util-optional:" +
            Versions.com_tailoredapps_androidutil

    /**
     * https://github.com/tailoredmedia/AndroidAppUtil
     */
    const val util_permissions: String = "com.tailoredapps.androidutil:util-permissions:" +
            Versions.com_tailoredapps_androidutil

    /**
     * https://github.com/tailoredmedia/AndroidAppUtil
     */
    const val util_ui: String = "com.tailoredapps.androidutil:util-ui:" +
            Versions.com_tailoredapps_androidutil

    /**
     * https://github.com/tailoredmedia/AndroidAppUtil
     */
    const val util_validation: String = "com.tailoredapps.androidutil:util-validation:" +
            Versions.com_tailoredapps_androidutil

    /**
     * https://github.com/tailoredmedia/AndroidAppUtil
     */
    const val util_viewstate: String = "com.tailoredapps.androidutil:util-viewstate:" +
            Versions.com_tailoredapps_androidutil

    const val buildsrcversions: String = "de.fayard:buildSrcVersions:" + Versions.buildsrcversions

    const val io_fabric_tools_gradle: String = "io.fabric.tools:gradle:" +
            Versions.io_fabric_tools_gradle

    /**
     * http://mockk.io
     */
    const val mockk: String = "io.mockk:mockk:" + Versions.mockk

    /**
     * https://github.com/ReactiveX/RxAndroid
     */
    const val rxandroid: String = "io.reactivex.rxjava2:rxandroid:" + Versions.rxandroid

    /**
     * https://github.com/ReactiveX/RxJava
     */
    const val rxjava: String = "io.reactivex.rxjava2:rxjava:" + Versions.rxjava

    /**
     * https://github.com/ReactiveX/RxKotlin
     */
    const val rxkotlin: String = "io.reactivex.rxjava2:rxkotlin:" + Versions.rxkotlin

    /**
     * https://github.com/wasabeef/glide-transformations
     */
    const val glide_transformations: String = "jp.wasabeef:glide-transformations:" +
            Versions.glide_transformations

    /**
     * http://junit.org
     */
    const val junit: String = "junit:junit:" + Versions.junit

    /**
     * https://github.com/saket/flick
     */
    const val flick: String = "me.saket:flick:" + Versions.flick

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_android_extensions_runtime: String =
            "org.jetbrains.kotlin:kotlin-android-extensions-runtime:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_android_extensions: String =
            "org.jetbrains.kotlin:kotlin-android-extensions:" + Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-compiler-embeddable:" + Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_stdlib_jdk7: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:" +
            Versions.org_jetbrains_kotlin

    const val koin_android: String = "org.koin:koin-android:" + Versions.org_koin

    const val koin_androidx_scope: String = "org.koin:koin-androidx-scope:" + Versions.org_koin

    const val koin_androidx_viewmodel: String = "org.koin:koin-androidx-viewmodel:" +
            Versions.org_koin

    const val koin_core: String = "org.koin:koin-core:" + Versions.org_koin

    const val koin_test: String = "org.koin:koin-test:" + Versions.org_koin
}
