import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val appcompat: String = "1.1.0"

    const val constraintlayout: String = "1.1.3"

    const val core_ktx: String = "1.1.0"

    const val fragment: String = "1.1.0"

    const val androidx_lifecycle: String = "2.1.0"

    const val androidx_navigation: String = "2.1.0"

    const val androidx_work: String = "2.2.0"

    const val koordinator_android_koin: String = "0.0.15"

    const val reaktor_android_koin: String = "1.1.0"

    const val easylauncher: String = "1.3.1"

    const val gesture_views: String = "2.5.2"

    const val customtabs: String = "28.0.0"

    const val aapt2: String = "3.5.3-5435860"

    const val bundletool: String = "0.10.2" // available: "0.12.0"

    const val com_android_tools_build_gradle: String = "3.5.3"

    const val lint_gradle: String = "26.5.3"

    const val crashlytics: String = "2.10.1"

    const val shimmer: String = "0.5.0"

    const val com_github_bumptech_glide: String = "4.10.0"

    const val rxpermissions: String = "0.10.2" // available: "2.x.v0.9.3"

    const val play_services_auth: String = "17.0.0"

    const val material: String = "1.0.0"

    const val com_google_android_play_core: String = "1.6.1" // available: "1.6.4"

    const val gson: String = "2.8.6"

    const val firebase_auth: String = "19.2.0"

    const val firebase_core: String = "17.2.1"

    const val firebase_dynamic_links: String = "19.0.0"

    const val firebase_firestore: String = "21.3.1"

    const val firebase_messaging: String = "20.1.0"

    const val firebase_perf: String = "19.0.4"

    const val google_services: String = "4.3.3"

    const val com_google_zxing_core: String = "3.4.0"

    const val com_jakewharton_rxbinding3: String = "3.1.0"

    const val rxrelay: String = "2.1.1"

    const val threetenabp: String = "1.2.1"

    const val timber: String = "4.7.1"

    const val zxing_android_embedded: String = "3.6.0" // available: "4.0.2"

    const val aboutlibraries: String = "6.2.1" // available: "8.0.0-a03"

    const val hawk: String = "2.0.1"

    const val ktlint: String = "0.36.0"

    const val leakcanary_android: String = "2.1"

    const val com_squareup_okhttp3: String = "4.3.0"

    const val com_squareup_retrofit2: String = "2.7.0"

    const val com_tailoredapps_androidutil: String = "16"

    const val buildsrcversions: String = "0.4.2"

    const val io_fabric_tools_gradle: String = "1.31.2"

    const val mockk: String = "1.9.3"

    const val rxandroid: String = "2.1.1"

    const val rxjava: String = "2.2.16"

    const val rxkotlin: String = "2.4.0"

    const val glide_transformations: String = "4.1.0"

    const val junit: String = "4.13"

    const val flick: String = "1.7.0"

    const val org_jetbrains_kotlin: String = "1.3.61"

    const val org_koin: String = "2.0.1"

    /**
     *
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.0.1"

    const val gradleCurrentVersion: String = "6.0.1"
}
